export const eventsList = [
  {
    name: "Недільне зібрання <br>(1-ша зміна)",
    day: "0",
    time: "9:30",
    location: "Фабрична 21",
    phone: "(320) 256 58 958",
    categories: ["all", "family", "children", "youth", "women"],
  },
  {
    name: "Недільне зібрання <br>(2-га зміна)",
    day: "0",
    time: "11:30",
    isOnline: true,
    location: "Фабрична 21",
    streamingPlatform: "Youtube",
    phone: "",
    categories: ["all", "family", "children", "youth", "women", "online"],
  },
  {
    name: "Недільна школа",
    day: "0",
    time: "11:30",
    isOnline: false,
    location: "Фабрична 21",
    phone: "+380634851287",
    categories: ["children"],
  },
  {
    name: "Молодіжка",
    day: "1",
    time: "19:00",
    isOnline: true,
    location: "Фабрична 21",
    streamingPlatform: "Youtube",
    phone: "",
    categories: ["youth", "online"],
  },
  {
    name: "Жіноча група",
    day: "1",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["women"],
  },
  {
    name: "Уроки царів",
    day: "2",
    time: "18:30",
    isOnline: true,
    streamingPlatform: "Zoom",
    phone: "+380634851287",
    categories: ["online"],
  },
  {
    name: "Домашня група",
    day: "3",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["youth"],
  },
  {
    name: "Домашня група",
    day: "3",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["youth"],
  },
  {
    name: "Домашня група",
    day: "3",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["youth"],
  },
  {
    name: "Домашня група",
    day: "3",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["youth"],
  },
  {
    name: "Домашня група",
    day: "3",
    time: "19:00",
    isOnline: false,
    location: "вул. Петлюри",
    phone: "+380634851287",
    categories: ["youth"],
  },
  {
    name: "Розбір Слова",
    day: "4",
    time: "18:00",
    isOnline: false,
    location: "Фабрична 21",
    phone: "+380634851287",
    categories: ["all", "family", "children", "youth", "women"],
  },
  {
    name: "Музична студія",
    day: "6",
    time: "18:00",
    isOnline: false,
    location: "Фабрична 21",
    phone: "+380634851287",
    categories: ["children"],
  },
];

export const categoriesNames = {
  all: "для всіх",
  family: "для сім'ї",
  children: "для дітей",
  youth: "для молоді",
  women: "для жінок",
  online: "онлайн",
};

export const categoriesColors = {
  all: "rgba(0, 105, 92, 1)",
  family: "rgba(40, 167, 69, 1)",
  children: "rgba(0, 153, 204, 1)",
  youth: "rgba(255, 193, 7, 1)",
  women: "rgba(153, 51, 204, 1)",
  online: "rgba(220, 53, 69, 1)",
};

export const socialCategoriesList = ["family", "children", "youth", "women"];